### ISSUE TITLE
Error on make -j build_franka=1

### ISSUE THREAD

**Issue by knezevicn** [UT-Austin-RPL/deoxys_control#1]
Hi, 

I tried couple of times to run your code but there is error when try to do make -j build_franka=1
Here is the output

`[ 67%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/utils/common_utils.cpp.o
[ 68%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/utils/control_utils.cpp.o
[ 69%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/utils/robot_utils.cpp.o
[ 69%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/utils/zmq_utils.cpp.o
[ 70%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/controllers/osc_impedance.cpp.o
[ 71%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/controllers/osc_position_impedance.cpp.o
[ 72%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/controllers/osc_yaw_impedance.cpp.o
[ 72%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/controllers/joint_position.cpp.o
[ 73%] Building CXX object CMakeFiles/shared_utils.dir/franka-interface/src/controllers/joint_impedance.cpp.o
/home/etfrobot/panda_ws/src/deoxys_control/deoxys/franka-interface/src/controllers/joint_impedance.cpp: In member function ‘virtual std::array<double, 7ul> controller::JointImpedanceController::Step(const franka::RobotState&, const Eigen::Matrix<double, 7, 1, 0>&)’:
/home/etfrobot/panda_ws/src/deoxys_control/deoxys/franka-interface/src/controllers/joint_impedance.cpp:95:50: warning: variable ‘t1’ set but not used [-Wunused-but-set-variable]
   std::chrono::high_resolution_clock::time_point t1 =
                                                  ^
[ 74%] Linking CXX static library libshared_utils.a
[ 74%] Built target shared_utils
[ 75%] Building CXX object CMakeFiles/franka-interface.dir/franka-interface/src/franka_control_node.cpp.o
In file included from /home/etfrobot/panda_ws/src/deoxys_control/deoxys/spdlog/include/spdlog/spdlog.h:12:0,
                 from /home/etfrobot/panda_ws/src/deoxys_control/deoxys/franka-interface/src/franka_control_node.cpp:16:
/home/etfrobot/panda_ws/src/deoxys_control/deoxys/spdlog/include/spdlog/common.h: In function ‘constexpr spdlog::string_view_t spdlog::details::to_string_view(const memory_buf_t&)’:
/home/etfrobot/panda_ws/src/deoxys_control/deoxys/spdlog/include/spdlog/common.h:350:42: error: call to non-constexpr function ‘const T* fmt::v9::detail::buffer<T>::data() const [with T = char]’
     return spdlog::string_view_t{buf.data(), buf.size()};
                                          ^
/home/etfrobot/panda_ws/src/deoxys_control/deoxys/franka-interface/src/franka_control_node.cpp: In function ‘int main(int, char**)’:
/home/etfrobot/panda_ws/src/deoxys_control/deoxys/franka-interface/src/franka_control_node.cpp:282:7: warning: unused variable ‘state_sub’ [-Wunused-variable]
     } state_sub{};
       ^
CMakeFiles/franka-interface.dir/build.make:75: recipe for target 'CMakeFiles/franka-interface.dir/franka-interface/src/franka_control_node.cpp.o' failed
make[3]: *** [CMakeFiles/franka-interface.dir/franka-interface/src/franka_control_node.cpp.o] Error 1
CMakeFiles/Makefile2:297: recipe for target 'CMakeFiles/franka-interface.dir/all' failed
make[2]: *** [CMakeFiles/franka-interface.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:42: recipe for target 'build' failed
make: *** [build] Error 2
`

**Comment by zhuyifengzju** [comment]
Hi,
    After reading your compilation information, it seems that the error comes from the `spdlog`, which is related to this issue: https://github.com/gabime/spdlog/issues/2142. Can you provide with more information on which version of spdlog you are using? I am using the branch `v1.x` on my end. And I would like to see if your version of spdlog is causing this issue.

**Comment by zhuyifengzju** [comment]
Please re-open this issue if you still have the issue or any one else continues to see the same issue.
