### ISSUE TITLE
while I run  ./auto_scripts/auto_arm.sh config/charmander.yml

### ISSUE THREAD

**Issue by lijinming2018** [UT-Austin-RPL/deoxys_control#11]
while I run  
./auto_scripts/auto_arm.sh config/charmander.yml

get 
  "
 Make sure you are in the Performance Mode!!!  
performance performance performance performance performance performance
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
bin/franka-interface: error while loading shared libraries: libyaml-cpp.so.0.8: cannot open shared object file: Error 40
"

**Comment by zhuyifengzju** [comment]
Please try this script https://github.com/UT-Austin-RPL/deoxys_control/blob/main/deoxys/auto_scripts/fix_ld_issue.sh

**Comment by praj441** [comment]
I was getting the same error. In my case, I solved it by disabling 'export' for ROS in .bashrc file. It seems the ROS things creating the problem. 

PS: First, I tried the advice by @zhuyifengzju , however, it didn't work.

**Comment by Msornerrrr** [comment]
Hi, I'm also having the same issue.
https://github.com/UT-Austin-RPL/deoxys_control/blob/main/deoxys/auto_scripts/fix_ld_issue.sh this script doesn't work and I don't have ROS on NUC
Thanks in advance!

**Comment by Siqi-Shang** [comment]
My fix was this: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

If you find other yaml-cpp with: ldconfig -p | grep yaml-cpp
Like:
libyaml-cpp.so.0.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libyaml-cpp.so.0.6
libyaml-cpp.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libyaml-cpp.so

The path with new install library (in my case /usr/local/lib/) should be added to the **END** of $LD_LIBRARY_PATH
