### ISSUE TITLE
Support Franka Research 3 Arm?

### ISSUE THREAD

**Issue by lif314** [UT-Austin-RPL/deoxys_control#15]
Thank you for your work, are there any plans to support  Franka Research 3 Arm?

**Comment by zhuyifengzju** [comment]
Hi, our lab does not have Research 3 arm, so I cannot test them locally. I believe there are other people using the new franka arms, and the codebase works fine on those.

**Comment by lif314** [comment]
> Hi, our lab does not have Research 3 arm, so I cannot test them locally. I believe there are other people using the new franka arms, and the codebase works fine on those.

Thank you for your reply! I will try it!

**Comment by tsrobcvai** [comment]
Supplement: Deoxys supports the lastest libfranka 0.13.3 in my practice

**Comment by rishoswal** [comment]
@tsrobcvai How were you able to use the latest libfranka? Did you just enter 0.13.3 when prompted by deoxys?

I believe I need libfranka 0.15.0 on robot system 5.7.2, does anyone know if deoxys supports libfranka 0.15.0.

Pardon my naivete, my first time setting up and working with FR3.

**Comment by zhuyifengzju** [comment]
you can just type in the full version number directly. Because it just specifies the exact branch name to check out to.

I believe as long as they haven't changed APIs, the codebase should compile. I don't have access to latest versions, so I cannot speak for the latest libfranka version.

**Comment by tsrobcvai** [comment]
> [@tsrobcvai](https://github.com/tsrobcvai) How were you able to use the latest libfranka? Did you just enter 0.13.3 when prompted by deoxys?
> 
> I believe I need libfranka 0.15.0 on robot system 5.7.2, does anyone know if deoxys supports libfranka 0.15.0.
> 
> Pardon my naivete, my first time setting up and working with FR3.

Hi, sorry that I didn't try 0.15.0, but you can go ahead with that as Yifeng suggested.

**Comment by chaitanyantr** [comment]
I'm looking for the support of 0.15.0 as well, as one tested it.?
I will update my findings in this thread.

**Comment by chaitanyantr** [comment]
![Image](https://github.com/user-attachments/assets/d1c0cefc-d2d7-4bf3-8437-9d2f298f6cb4)

**Comment by chaitanyantr** [comment]
![Image](https://github.com/user-attachments/assets/3fe3db6d-ed35-4903-9150-897fe3d71011)

**Comment by rishoswal** [comment]
Hey, I was able to use libfranka 0.15.0 by just installing pinocchio detailed in step 2 from this [link](https://github.com/frankaemika/libfranka/blob/main/README.md).

Let me know if you have any questions.

**Comment by s-m-asjad** [comment]
This is a note to folks using the FR3 with deoxys... that by default deoxys applies the FP3 joint limits (at least in joint impedance mode). The picture below is a sinusoidal signal to joint 6 with all other joints stationary and the clipping happens at the FP3 joint limit. We verified by bumping the joint with our hands that it is capable of reaching a higher joint position.

<img width="639" height="479" alt="Image" src="https://github.com/user-attachments/assets/1e64eb24-f130-4664-a99e-fc305c9208b1" />

**Comment by hesic73** [comment]
I'm able to use deoxys to control the Franka Research 3 with libfranka `0.15.3`. While joint position and impedance control seem to work fine, I suspect there might be issues with osc and parts involving forward and inverse kinematics.

For instance, the ik wrapper appears to use an older robot's MJCF file for its calculations. The ee pose I get from the deoxys API is different from the value I compute using Pinocchio.


```python
import pinocchio as pin
import numpy as np


class FrankaKinematics:
    def __init__(self, urdf_path):
        self.model = pin.buildModelFromUrdf(urdf_path)
        self.data = self.model.createData()
        self.nq = self.model.nq
        self.end_effector_frame_id = self.model.getFrameId("fr3_link8")

    def fk(self, joint_angles):
        q = np.array(joint_angles)
        pin.forwardKinematics(self.model, self.data, q)
        pin.updateFramePlacements(self.model, self.data)

        end_effector_placement = self.data.oMf[self.end_effector_frame_id]

        position = end_effector_placement.translation
        quaternion = pin.Quaternion(end_effector_placement.rotation)

        return position, quaternion.coeffs()


if __name__ == '__main__':
    urdf_path = "fr3.urdf"

    franka_kin = FrankaKinematics(urdf_path)

    joint_angles = [0.0955204, -0.19500057, -0.02151408, -2.47519644, -0.01144905,
                    2.30812684,  0.85063031]
    position, quaternion = franka_kin.fk(joint_angles)

    print("FK Results:")
    print("Position (x, y, z):", position)
    print("Quaternion (x, y, z, w):", quaternion)

```

The output of the script is:

```bash
FK Results:
Position (x, y, z): [0.45452847 0.03351381 0.36694372]
Quaternion (x, y, z, w): [ 0.92695075 -0.37491708  0.01346962 -0.00424984]
```

However, when I use the deoxys API to get the EE pose for the same joint angles, the result is:

```bash
 [ 0.45755272  0.03329227  0.26365091  3.13890052 -0.02812072  0.01674069]
```

The z position is significantly different, and the rotation doesn't match either. Could this be because I'm using a different EE link?

**Comment by hesic73** [comment]
> This is a note to folks using the FR3 with deoxys... that by default deoxys applies the FP3 joint limits (at least in joint impedance mode). The picture below is a sinusoidal signal to joint 6 with all other joints stationary and the clipping happens at the FP3 joint limit. We verified by bumping the joint with our hands that it is capable of reaching a higher joint position.
> 
> <img alt="Image" width="639" height="479" src="https://private-user-images.githubusercontent.com/83300310/472135646-1e64eb24-f130-4664-a99e-fc305c9208b1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyODg5NTAsIm5iZiI6MTc1NjI4ODY1MCwicGF0aCI6Ii84MzMwMDMxMC80NzIxMzU2NDYtMWU2NGViMjQtZjEzMC00NjY0LWE5OWUtZmMzMDVjOTIwOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI3VDA5NTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNDc1N2MxNjM1ZjRmYWFkMGM0YzYxNzJhMDE2MTg3YmNkZTkwMzAzZTE5NGY4OGZhZmY0ZDczODNhZThlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.31Gl7_I0GWEJE7CKm5SPGLlIDKnxW9n5q5so7z7d_t4">

Just find that it's hard-coded here:

https://github.com/UT-Austin-RPL/deoxys_control/blob/97396fd91324e9e961f061544e80a208889526ff/deoxys/franka-interface/src/controllers/joint_impedance.cpp#L61-L62

**Comment by s-m-asjad** [comment]
> 
> Just find that it's hard-coded here:
> 
> [deoxys_control/deoxys/franka-interface/src/controllers/joint_impedance.cpp](https://github.com/UT-Austin-RPL/deoxys_control/blob/97396fd91324e9e961f061544e80a208889526ff/deoxys/franka-interface/src/controllers/joint_impedance.cpp#L61-L62)
> 
> Lines 61 to 62 in [97396fd](/UT-Austin-RPL/deoxys_control/commit/97396fd91324e9e961f061544e80a208889526ff)
> 
>  joint_max_ << 2.8978, 1.7628, 2.8973, -0.0698, 2.8973, 3.7525, 2.8973; 
>  joint_min_ << -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973;

That is correct, we also had to change that in the file you mentioned. Thank you for sharing the fix 👍

**Comment by kingchou007** [comment]
> I'm able to use deoxys to control the Franka Research 3 with libfranka `0.15.3`. While joint position and impedance control seem to work fine, I suspect there might be issues with osc and parts involving forward and inverse kinematics.
> 
> For instance, the ik wrapper appears to use an older robot's MJCF file for its calculations. The ee pose I get from the deoxys API is different from the value I compute using Pinocchio.
> 
> import pinocchio as pin
> import numpy as np
> 
> 
> class FrankaKinematics:
>     def __init__(self, urdf_path):
>         self.model = pin.buildModelFromUrdf(urdf_path)
>         self.data = self.model.createData()
>         self.nq = self.model.nq
>         self.end_effector_frame_id = self.model.getFrameId("fr3_link8")
> 
>     def fk(self, joint_angles):
>         q = np.array(joint_angles)
>         pin.forwardKinematics(self.model, self.data, q)
>         pin.updateFramePlacements(self.model, self.data)
> 
>         end_effector_placement = self.data.oMf[self.end_effector_frame_id]
> 
>         position = end_effector_placement.translation
>         quaternion = pin.Quaternion(end_effector_placement.rotation)
> 
>         return position, quaternion.coeffs()
> 
> 
> if __name__ == '__main__':
>     urdf_path = "fr3.urdf"
> 
>     franka_kin = FrankaKinematics(urdf_path)
> 
>     joint_angles = [0.0955204, -0.19500057, -0.02151408, -2.47519644, -0.01144905,
>                     2.30812684,  0.85063031]
>     position, quaternion = franka_kin.fk(joint_angles)
> 
>     print("FK Results:")
>     print("Position (x, y, z):", position)
>     print("Quaternion (x, y, z, w):", quaternion)
> The output of the script is:
> 
> FK Results:
> Position (x, y, z): [0.45452847 0.03351381 0.36694372]
> Quaternion (x, y, z, w): [ 0.92695075 -0.37491708  0.01346962 -0.00424984]
> However, when I use the deoxys API to get the EE pose for the same joint angles, the result is:
> 
>  [ 0.45755272  0.03329227  0.26365091  3.13890052 -0.02812072  0.01674069]
> The z position is significantly different, and the rotation doesn't match either. Could this be because I'm using a different EE link?

Any Solution?

**Comment by s-m-asjad** [comment]
@kingchou007 the forward kinematics solution for FR3 and FP3 should be the same. Does your urdf contain the FR3/Panda gripper? That will change the z position and the orientation.

**Comment by kingchou007** [comment]
> [@kingchou007](https://github.com/kingchou007) the forward kinematics solution for FR3 and FP3 should be the same. Does your urdf contain the FR3/Panda gripper? That will change the z position and the orientation.

I see!!!! Thanks.
