### ISSUE TITLE
    self.roll = convert(d[7], d[8]) IndexError: list index out of range

### ISSUE THREAD

**Issue by lijinming2018** [UT-Austin-RPL/deoxys_control#16]
when I run python examples/run_deoxys_with_space_mouse.py 
I get 
pybullet build time: May 20 2022 19:44:17
Opening SpaceMouse device
Manufacturer: 3Dconnexion
Product: SpaceMouse Compact

Control                       	Command
Right button                  	reset simulation
Left button (hold)            	close gripper
Move mouse laterally          	move arm horizontally in x-y plane
Move mouse vertically         	move arm vertically
Twist mouse about an axis     	rotate arm about a corresponding axis
ESC                           	quit

7
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/rl/miniconda3/envs/deoxys/lib/python3.8/threading.py", line 932, in _bootstrap_inner
OSC_POSE
    self.run()
  File "/home/rl/miniconda3/envs/deoxys/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rl/Documents/deoxys_control/deoxys/deoxys/utils/io_devices/spacemouse.py", line 236, in run
    self.roll = convert(d[7], d[8])
IndexError: list index out of range

**Comment by praj441** [comment]
Hi,

I was getting a similar issue. Probabily its because of your space mouse version.
See the discussion [here](https://github.com/UT-Austin-RPL/deoxys_control/issues/14#issue-2021694378).

**Comment by jstmn** [comment]
~~Hey @praj441 how did you fix this? I'm getting the same error. I have `--vendor-id 9583 --product-id 50741` for my spacemouse~~

The solution is to copy the code from here: https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/devices/spacemouse.py#L254C39-L254C44
