### ISSUE TITLE
Robosuite compatibilty !

### ISSUE THREAD

**Issue by praj441** [UT-Austin-RPL/deoxys_control#18]
@zhuyifengzju 
I have a simple question.

In the ReadMe, it is written that "**If you are a [robosuite](https://github.com/ARISE-Initiative/robosuite) user, Deoxys APIs provide seamless transfer from you simulation codebase to real robot experiments!**"

I am not able to find any such information or tutorial in the documentation.
What do the lines actually mean? Is it for sim2real transfer or transfer of codebase from RoboSuite to the Deoxys pipeline? Please explain.

**Comment by zhuyifengzju** [comment]
This means more about changing your code from simulation to real robot. More specifically: 1) the way you curate learning policies and the action format will be very similar; 2) the control loop in the python end is similar for both robosuite and deoxys.

**Comment by praj441** [comment]
@zhuyifengzju 
Thanks for the info.
