### ISSUE TITLE
ModuleNotFoundError: No module named 'rpl_vision_utils'

### ISSUE THREAD

**Issue by praj441** [UT-Austin-RPL/deoxys_control#19]
It seems the particular module is missing from the codebase.
Any plans for adding it to the codebase?

Thanks!

**Comment by zhuyifengzju** [comment]
Thanks for pointing this out. I think this is legacy changes I need to change it. The thing I plan to release is renamed to `deoxys_vision`, but it might take more time to get ready.

**Comment by praj441** [comment]
@zhuyifengzju 
Thanks for the reply. Looking forward to the deoxys_vision package.
