### ISSUE TITLE
Robosuite to real arm implementation

### ISSUE THREAD

**Issue by Soha18** [UT-Austin-RPL/deoxys_control#7]
Hi,

Thank you for this repository..
I'm trying to deploy a RL model that is trained on robosuite environment to a real Panda arm.
my settings: environment: Lift, controller OSC-POSE, is_delta= True, the model gets  observations (42,) as input and outputs actions (7,)
- How to get `eef_pos` and` eef_quat` to include it in the observations (is it in base frame or in world frame which are not consistent in the simulator, also it is not clear if it comes from `gripper_eef` or from` hand_pose`).  would I use FrankaState msg O_T_EE or another one.
- I calculated the target pose from the model's output actions in the same way you did but it did not work (there is extra rotation when it gets close to the object), while the actions output represents 'delta_pose' in position and axis angles, is it in world frame or base frame? do I need to get delta pose in base frame first?

Many thanks, and I appreciate any help.

regards

**Comment by zhuyifengzju** [comment]
Hi, yes everything in deoxys codebase is based on `libfranka`, which is in the base frame. For getting `eef_pos` and `eef_quat`, you can look at : [https://github.com/UT-Austin-RPL/deoxys_control/blob/aa5f1aff12ea09b0c2fa3799b7b0b524a6212b0d/deoxys/deoxys/franka_interface/franka_interface.py#L536](url), which are basically `O_T_EE`. I think the thing you can check is to set the robot to the same joints as in the simulator, and see the end effector values. This will give you an idea what are the mismatch, and which link is used in robosuite for end effector pose (it's not on top of my head, and I need to take a closer look later).

Can you elaborate more on "extra rotation" you mentioned? It could be that the rotation is not taken care of carefully --- there is this -2pi ~ 2pi discontinuity issue that you need to handle.
